### ISSUE TITLE
docs and README.md is missing

### ISSUE THREAD

**Issue by deknos** [lhm-limux/reprepro-bundle-tools#1]
Hi,
rudimentary documentation for dependencies and base system and how to use it would be nice. also which use case differentiates it from, for example aptly.

**Comment by chrlutz** [comment]
Hi deknos,

nice to see you are interested :-)

README.md was added yesterday. Still not answering some of your questions:

* base system: a debian based system (stretch or bionic would be good) with just some few dependencies installed - packages like reprepro, python3-jinja2, maybe some more python3-libs

* usage infos: puhh... "./bin/bundle -h" and "./bin/bundle-compose -h" and a look at the examples in test/Makefile must be sufficient for the moment. I have to write the internal documentation first (which is still missing).

* different use case from aptly: Most important difference is the concept of *bundles* which can contain multiple debian packages (including their sources) and where a bundle contains all outputs from a distribution maintainer "development task" (e.g. security-update, working on a ticket, ...). The most important feature is the ability to have a kind of staging mechanism and to put bundles to different targets depending on their status in the workflow. One could argue that aptly can do the same things - this could be possible. I don't know too much about aptly. I don't like the complex setup to get all aptly services running correctly. Reprepro is a lightweight tool that could be used directly from the command line without having any services running. The bundle-tools don't necessarily require a server, too (but could be combined with a server). You can see in the example "test" suite that reprepro management is still possible with file://-urls. Another interesting point is the ability to track all distro changes in a git-repository.

atb,
Christoph

**Comment by chrlutz** [comment]
just updated the README file. Infos from above have been merge to there and are documented more verbose now. I think all questions from above are answered now.
